(* Reference: EBNF: ISO/IEC 14977:1996(E)            *)
(*   https://www.cl.cam.ac.uk/~mgk25/iso-14977.pdf   *)


(*  Top level  *)

module = { annotation } , { decl } ;

decl = func-decl
     | extern-block
     | top-var-decl
     | top-const-decl
     | annotation ;

top-var-decl = ident , ":", type , [ "=" , expr ] , ";" ;

top-const-decl = ident , "::" , expr , ";" ;


(*  Declarations  *)

func-decl = ident , "::" , "(" , param-list , ")" , "->" , type , block-stmt ;

extern-block = "extern" , "{" , extern-decl , { "," , extern-decl } , "}"
             | "extern" , extern-decl , ";" ;

extern-decl = ident , "(" , param-list , ")" , "->" , type ;

param-list = (* empty *)
           | param , { "," , param } ;

param = [ ident , ":" ] , type , [ "=" , expr ]
      | "..." , [ ident , ":" , type ] ;


(*  Annotations  *)

annotation = "#" , ident , [ "(" , annotation-args , ")" ] ;

annotation-args = (* anything *) ;


(*  Types  *)

(* Prefix letter determines type family; optional bits suffix  *)
(* defaults to 64 when omitted.                                *)

type = base-type
     | "*" , [ "!" ] , type               (* pointer type; *!T is non-null *)
     | "[" , type , "]"                   (* array type [T]  *)
     | "[" , type , ";" , int-lit , "]"   (* array type [T;N]*)
     | "!" ;                              (* never type      *)

base-type = "void"
          | int-type
          | float-type ;

int-type = ( "i" | "s" ) , [ bits ]   (* signed integer   *)
         | "u" , [ bits ] ;           (* unsigned integer *)

float-type = "f" , [ bits ] ;

bits = digit , { digit } ;    (* any value in 0..65535 *)

(*  Statements  *)

stmt = block-stmt
     | if-stmt
     | while-stmt
     | for-stmt
     | return-stmt
     | stmt-var-decl
     | stmt-const-decl
     | var-assign
     | index-assign
     | expr-stmt ;

block-stmt = "{" , { stmt } , "}" ;

if-stmt = "if" , expr , stmt , [ "else" , stmt ] ;

while-stmt = "while" , expr , stmt ;

for-stmt = "for" , ident , ":" , expr , stmt ;

return-stmt = "return" , [ expr ] , ";" ;

stmt-var-decl = ident , ":" , type , [ "=" , expr ] , ";"
              | ident , ":=" , expr , ";" ;

stmt-const-decl = ident , "::" , type , [ "=" , expr ] , ";" ;

var-assign = ident , assign-op , expr , ";" ;

index-assign = ident , { postfix-op } , "[" , expr , "]" , assign-op , expr , ";" ;

assign-op = "=" | "+=" | "-=" | "*=" | "/=" | "%="
          | "&=" | "|=" | "^=" | "~=" | "<<=" | ">>="
          | "**=" | "&&=" | "||=" ;

expr-stmt = expr , ";" ;


(*  Expressions  (precedence low -> high, all left-associative)  *)

expr = range ;

range = logical-or , [ ( ".." | "..<" ) , logical-or , [ ":" , logical-or ] ] ;

logical-or = logical-and , { "||" , logical-and } ;

logical-and = bitwise-or , { "&&" , bitwise-or } ;

bitwise-or = bitwise-xor , { "|" , bitwise-xor } ;

bitwise-xor = bitwise-and , { "^" , bitwise-and } ;

bitwise-and = equality , { "&" , equality } ;

equality = relational , { equality-op , relational } ;

equality-op = "==" | "!=" ;

relational = shift , { relational-op , shift } ;

relational-op = "<" | "<=" | ">" | ">=" ;

shift = additive , { shift-op , additive } ;

shift-op = "<<" | ">>" ;

additive = multiplicative , { additive-op , multiplicative } ;

additive-op = "+" | "-" ;

multiplicative = power , { multiplicative-op , power } ;

multiplicative-op = "*" | "/" | "%" ;

power = unary , { "**" , unary } ;

(* Unary is right-recursive to allow chaining: --x, +-x, etc. *)
unary = unary-op , unary
      | postfix ;

unary-op = "-" | "+" | "!" | "~" | "&" | "*" | "++" | "--" ;

postfix = primary , { postfix-op } ;

postfix-op = "[" , expr , "]"              (* array indexing  *)
           | "(" , arg-list , ")"          (* function call    *)
           | "." , ident                   (* member access    *)
           | "as" , ( type | "?" )         (* cast operator    *)
           | "++"                          (* postfix increment *)
           | "--" ;                        (* postfix decrement *)


(*  Primary expressions  *)

primary = int-lit
        | float-lit
        | str-lit
        | array-lit
        | ident
        | "nullptr"
        | "(" , expr , ")" ;

array-lit = "[" , [ expr , { "," , expr } ] , "]" ;

call = ident , "(" , arg-list , ")" ;

arg-list = (* empty *)
         | expr , { "," , expr } ;


(*  Literals  *)

int-lit = digits , [ int-suffix ] ;

int-suffix = "u" , digits    (* unsigned, e.g. 42u8  *)
           | "i" , digits ;  (* signed,   e.g. 42i32 *)

float-lit = digits , "." , digits , [ float-suffix ] ;

float-suffix = "f" , digits ;  (* e.g. 3.14f32 *)

digits = digit , { digit } ;

digit = "0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9" ;

str-lit = { str-prefix } , "\"" , { character } , "\"" ;

str-prefix = "c" | "b" | "r" | "m" ;  (* c=cstr, b=bytes, r=raw, m=multiline *)

ident = letter , { letter | digit | "_" } ;

letter = "a" | "b" | "c" | "d" | "e" | "f" | "g" | "h" | "i"
       | "j" | "k" | "l" | "m" | "n" | "o" | "p" | "q" | "r"
       | "s" | "t" | "u" | "v" | "w" | "x" | "y" | "z"
       | "A" | "B" | "C" | "D" | "E" | "F" | "G" | "H" | "I"
       | "J" | "K" | "L" | "M" | "N" | "O" | "P" | "Q" | "R"
       | "S" | "T" | "U" | "V" | "W" | "X" | "Y" | "Z" ;


(*  Reserved words  (may not be used as ident)  *)

(* "if"      - if-stmt keyword                                  *)
(* "else"    - else branch keyword                              *)
(* "while"   - while-stmt keyword                               *)
(* "for"     - for-stmt keyword                                 *)
(* "return"  - return-stmt keyword                              *)
(* "extern"  - extern declaration keyword                       *)
(* "void"    - type keyword                                     *)
(* "as"      - cast operator keyword                            *)
(* "nullptr" - null pointer literal                             *)
